[project]
name = "gitlint-config"
dynamic = ["version"]
description = "ğŸ™âš™ï¸ ha8ta6's Gitlint configuration."
readme = "README.md"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = []
